### ISSUE TITLE
Figure 2 in the paper (CKA)

### ISSUE THREAD

**Issue by Zhengsh123** [gstoica27/KnOTS#8]
Could you please clarify the experimental setup for Figure 2 in the paper? I tested the fine-tuning results of CLIP's ViT-B-16 on these datasets. **The CKA of the model after loading different LoRA modules doesn't seem to be much lower than the fully fine-tuned model.**  The test dataset I used is ImageNet. Could it be that I've overlooked something?

The two images attached below are the results of my tests: the first one shows the fully fine-tuned results, and the second one shows the LoRA fine-tuning results.

Fully fine-tuned results:
![full_cka](https://shz-image.oss-cn-beijing.aliyuncs.com/full_cka.png)

LoRA fine-tuned results:
![lora_cka](https://shz-image.oss-cn-beijing.aliyuncs.com/lora_cka.png)

**Comment by gstoica27** [comment]
Hi, 

Could you say more about how specifically you generated these figures and also more about the models used? 

For instance, how did you compute the fully fine-tuned CKA figure (the top figure)? Similarly, on which particular activations are you computing CKA over? For the latter, are you performing this on only the LoRA activations, or the activations of the layer + LoRA (i.e.., what have you placed the forward hook on)? 

Regarding the figures, it's worth noting (unless I'm mistaken by your post) that these LoRAs were not trained on ImageNet? Rather I presume only on each of the 8 datasets considered in the heat maps? Passing in out-of-distribution data can cause unexpected behavior -- would you expect any of the LoRAs to support ImageNet? 

Lastly, although the CKAs are comparable for several pairwise models in your post, there are still certain LoRA models that are dramatically less aligned than in the fully fine-tuned scenario, even on ImageNet. Btw, it looks like SUN397 (which from what I understand is the most similar dataset to ImageNet) has among the lowest CKAs compared to the other datasets whose distributions are quite dissimilar (e.g., EuroSAT and RESIC45).

**Comment by Zhengsh123** [comment]
Thank you very much for your prompt response. Next, I will briefly describe the way I calculate CKA.

In fact, I calculate the CKA similarity between two models by adding the LoRA fine-tuned on each of the 8 datasets shown in the figure to the base model, then extracting the activations from the final layer. The horizontal and vertical axes represent the fine-tuning datasets, similar to the meaning of Figure 2 in your paper. The reason for computing on ImageNet is to find a general dataset for the calculation (or, in your case, how did you choose the dataset for this computation?).

My concern is that the representation similarity of the LoRA fine-tuned models I computed seems significantly higher than what is shown in Figure 2. Could this be due to a mistake in my setup? If possible, could you share how you performed your calculations? 

Best regards,
Shenghe

**Comment by gstoica27** [comment]
Oh I see, we compute the CKA in a completely different way. Have you looked at Appendix B of our paper? We describe the exact steps there. Sorry that this wasn't clear in the paper! I also see that we do not reference to the Appendix in the main paper -- we should fix that 😅.

Specifically, we pass in data from all 8 datasets into each LoRA model, and then _only_ compute CKA on the activations of the LoRA layers of each model. For the fully fine-tuned model (FFT) case, we hook into the same layers we'd apply LoRA on, and subtract the activations of the retrained model from the activations of the FFT model for the same data. Does this make sense? More details are in that Appendix, but I'd be happy to answer any follow ups! 

Btw, I'd think it would not that surprising that the CKAs of the final layer are generally quite high. Transformers are extremely "flat" networks, if you compute CKA off the final layer, you are computing the CKA off of the sum of many residual pathways that do not necessarily interact with the LoRA modules directly. In addition though, different data can also lead to different CKA results -- it's very data dependent due to reliance on activations.

**Comment by Zhengsh123** [comment]
Thank you very much for your prompt response. I now understand the differences in our calculation methods. The KnOTS you have completed is quiet an excellent work!

**Comment by Zhengsh123** [comment]
Thank you very much for your prompt response. I now understand the differences in our calculation methods. The KnOTS you have completed is quiet an excellent work!
